initParms <- function(newParms = NULL) {
  parms <- c(
    MW_APAP = 151.17,
    MW_AG = 327.28,
    MW_AS = 231.22,
    BW = 70.,
    lnBW = 0.0,
    QCC = 16.2,
    VFC = 0.214,
    VKC = 0.0044,
    VGC = 0.0144,
    VLC = 0.0257,
    VMC = 0.4,
    VBLAC = 0.0243,
    VBLVC = 0.0557,
    VSC = 0.185,
    VRC = 0.0765,
    QFC = 0.052,
    QKC = 0.175,
    QGC = 0.181,
    QLBC = 0.046,
    QMC = 0.191,
    QSC = 0.14,
    QRC = 0.215,
    kSG_Vm = 2332.5,
    lnkSG_Vm = 0.0,
    kSG_Km = 1765.49,
    lnkSG_Km = 0.0,
    Tg = 0,
    lnTg = -1.0,
    Tp = 0,
    lnTp = -3.0,
    CLC_APAP = 0,
    lnCLC_APAP = -2.0,
    CLC_AS = 0,
    lnCLC_AS = -2.0,
    CLC_AG = 0,
    lnCLC_AG = -2.0,
    alpha_APAP = 1.,
    alpha_AS = 1.,
    alpha_AG = 1.,
    BP_APAP = 0.9,
    lnBP_APAP = 0.0,
    PF_APAP = 0.447,
    lnPF_APAP = 0.0,
    PG_APAP = 0.907,
    lnPG_APAP = 0.0,
    PK_APAP = 0.711,
    lnPK_APAP = 0.0,
    PL_APAP = 0.687,
    lnPL_APAP = 0.0,
    PM_APAP = 0.687,
    lnPM_APAP = 0.0,
    PR_APAP = 0.676,
    lnPR_APAP = 0.0,
    PS_APAP = 0.606,
    lnPS_APAP = 0.0,
    PF_AS = 0.088,
    lnPF_AS = 0.0,
    PG_AS = 0.297,
    lnPG_AS = 0.0,
    PK_AS = 0.261,
    lnPK_AS = 0.0,
    PL_AS = 0.203,
    lnPL_AS = 0.0,
    PM_AS = 0.199,
    lnPM_AS = 0.0,
    PR_AS = 0.207,
    lnPR_AS = 0.0,
    PS_AS = 0.254,
    lnPS_AS = 0.0,
    PF_AG = 0.128,
    lnPF_AG = 0.0,
    PG_AG = 0.436,
    lnPG_AG = 0.0,
    PK_AG = 0.392,
    lnPK_AG = 0.0,
    PL_AG = 0.321,
    lnPL_AG = 0.0,
    PM_AG = 0.336,
    lnPM_AG = 0.0,
    PR_AG = 0.364,
    lnPR_AG = 0.0,
    PS_AG = 0.351,
    lnPS_AG = 0.0,
    kPAPS = 0.018,
    lnkPAPS = 0.0,
    kPAPS_syn = 0,
    lnkPAPS_syn = -30,
    kGA = 0.008,
    lnkGA = 0.0,
    kGA_syn = 0,
    lnkGA_syn = -30,
    CYP_Km = 0,
    lnCYP_Km = 7.6,
    CYP_VmaxC = 0,
    lnCYP_VmaxC = 8.4,
    UGT_Km = 0,
    lnUGT_Km = 9,
    UGT_Ki = 0,
    lnUGT_Ki = 23,
    UGT_VmaxC = 0,
    lnUGT_VmaxC = 7.3,
    UGT_Km_GA = 0,
    lnUGT_Km_GA = 2.3,
    Vmax_AG = 0,
    lnVmax_AG = 30,
    Km_AG = 0,
    lnKm_AG = 9.9,
    SULT_Km_apap = 0,
    lnSULT_Km_apap = 3.0,
    SULT_Km_paps = 0,
    lnSULT_Km_paps = 3.0,
    SULT_Ki = 0,
    lnSULT_Ki = 20,
    SULT_VmaxC = 0,
    lnSULT_VmaxC = 10,
    Vmax_AS = 0,
    lnVmax_AS = 20,
    Km_AS = 0,
    lnKm_AS = 10,
    mgkg_flag = 1.,
    OralDose_APAP_mgkg = 1,
    OralDose_APAP_mg = 1,
    OralDur_APAP = 0.001,
    ODose_APAP_mg = 0,
    fa = 0,
    ODose_APAP = 0,
    true_dose = 0,
    IVDose_APAP_mgkg = 0.,
    lnIVDose_APAP_mgkg = 0.0,
    IVDose_APAP_mg = 0.,
    lnIVDose_APAP_mg = 0.0,
    IVDur_APAP = 0.001,
    IVD_APAP_mg = 0,
    IVDR_APAP = 0,
    CYP_Vmax = 0,
    UGT_Vmax = 0,
    SULT_Vmax = 0,
    VTC = 0,
    VF = 0,
    VK = 0,
    VG = 0,
    VM = 0,
    VL = 0,
    VBLA = 0,
    VBLV = 0,
    VR = 0,
    VS = 0,
    QTC = 0,
    QC = 0,
    QF = 0,
    QK = 0,
    QG = 0,
    QM = 0,
    QLB = 0,
    QR = 0,
    QS = 0,
    QL = 0,
    CLR_APAP = 0,
    CLR_AS = 0,
    CLR_AG = 0,
    M_OralDose_APAP = 0,
    Var_OralDose_APAP = 0,
    M_IVDose_APAP = 0,
    Var_IVDose_APAP = 0,
    M_lnOralDose_APAP = 0,
    Var_lnOralDose_APAP = 0,
    M_lnIVDose_APAP = 0,
    M_lnVar_IVDose_APAP = 0,
    M_BW = 0,
    M_lnBW = 0,
    M_fa = 0,
    M_lnfa = 0,
    M_kSG_Vm = 0,
    M_lnkSG_Vm = 0,
    M_kSG_Km = 0,
    M_lnkSG_Km = 0,
    M_Tg = 0,
    M_lnTg = 0,
    M_Tp = 0,
    M_lnTp = 0,
    M_CLC_APAP = 0,
    M_lnCLC_APAP = 0,
    M_CLC_AS = 0,
    M_lnCLC_AS = 0,
    M_CLC_AG = 0,
    M_lnCLC_AG = 0,
    M_BP_APAP = 0,
    M_lnBP_APAP = 0,
    M_PF_APAP = 0,
    M_lnPF_APAP = 0,
    M_PG_APAP = 0,
    M_lnPG_APAP = 0,
    M_PK_APAP = 0,
    M_lnPK_APAP = 0,
    M_PL_APAP = 0,
    M_lnPL_APAP = 0,
    M_PM_APAP = 0,
    M_lnPM_APAP = 0,
    M_PR_APAP = 0,
    M_lnPR_APAP = 0,
    M_PS_APAP = 0,
    M_lnPS_APAP = 0,
    M_PK_AS = 0,
    M_lnPK_AS = 0,
    M_PF_AS = 0,
    M_lnPF_AS = 0,
    M_PL_AS = 0,
    M_lnPL_AS = 0,
    M_PG_AS = 0,
    M_lnPG_AS = 0,
    M_PM_AS = 0,
    M_lnPM_AS = 0,
    M_PR_AS = 0,
    M_lnPR_AS = 0,
    M_PS_AS = 0,
    M_lnPS_AS = 0,
    M_PK_AG = 0,
    M_lnPK_AG = 0,
    M_PF_AG = 0,
    M_lnPF_AG = 0,
    M_PL_AG = 0,
    M_lnPL_AG = 0,
    M_PG_AG = 0,
    M_lnPG_AG = 0,
    M_PM_AG = 0,
    M_lnPM_AG = 0,
    M_PR_AG = 0,
    M_lnPR_AG = 0,
    M_PS_AG = 0,
    M_lnPS_AG = 0,
    M_kPAPS = 0,
    M_lnkPAPS = 0,
    M_kPAPS_syn = 0,
    M_lnkPAPS_syn = 0,
    M_kGA = 0,
    M_lnkGA = 0,
    M_kGA_syn = 0,
    M_lnkGA_syn = 0,
    M_CYP_Km = 0,
    M_lnCYP_Km = 0,
    M_CYP_VmaxC = 0,
    M_lnCYP_VmaxC = 0,
    M_UGT_Km = 0,
    M_lnUGT_Km = 0,
    M_UGT_VmaxC = 0,
    M_lnUGT_VmaxC = 0,
    M_UGT_Km_GA = 0,
    M_lnUGT_Km_GA = 0,
    M_UGT_Ki = 0,
    M_lnUGT_Ki = 0,
    M_Vmax_AG = 0,
    M_lnVmax_AG = 0,
    M_Km_AG = 0,
    M_lnKm_AG = 0,
    M_SULT_Km_apap = 0,
    M_lnSULT_Km_apap = 0,
    M_SULT_Km_paps = 0,
    M_lnSULT_Km_paps = 0,
    M_SULT_Ki = 0,
    M_lnSULT_Ki = 0,
    M_SULT_VmaxC = 0,
    M_lnSULT_VmaxC = 0,
    M_Vmax_AS = 0,
    M_lnVmax_AS = 0,
    M_Km_AS = 0,
    M_lnKm_AS = 0,
    Var_BW = 0,
    Var_lnBW = 0,
    Var_fa = 0,
    Var_lnfa = 0,
    Var_kSG_Vm = 0,
    Var_lnkSG_Vm = 0,
    Var_kSG_Km = 0,
    Var_lnkSG_Km = 0,
    Var_Tg = 0,
    Var_lnTg = 0,
    Var_Tp = 0,
    Var_lnTp = 0,
    Var_CLC_APAP = 0,
    Var_lnCLC_APAP = 0,
    Var_CLC_AS = 0,
    Var_lnCLC_AS = 0,
    Var_CLC_AG = 0,
    Var_lnCLC_AG = 0,
    Var_BP_APAP = 0,
    Var_lnBP_APAP = 0,
    Var_PF_APAP = 0,
    Var_lnPF_APAP = 0,
    Var_PG_APAP = 0,
    Var_lnPG_APAP = 0,
    Var_PK_APAP = 0,
    Var_lnPK_APAP = 0,
    Var_PL_APAP = 0,
    Var_lnPL_APAP = 0,
    Var_PM_APAP = 0,
    Var_lnPM_APAP = 0,
    Var_PR_APAP = 0,
    Var_lnPR_APAP = 0,
    Var_PS_APAP = 0,
    Var_lnPS_APAP = 0,
    Var_PK_AS = 0,
    Var_lnPK_AS = 0,
    Var_PF_AS = 0,
    Var_lnPF_AS = 0,
    Var_PL_AS = 0,
    Var_lnPL_AS = 0,
    Var_PG_AS = 0,
    Var_lnPG_AS = 0,
    Var_PM_AS = 0,
    Var_lnPM_AS = 0,
    Var_PR_AS = 0,
    Var_lnPR_AS = 0,
    Var_PS_AS = 0,
    Var_lnPS_AS = 0,
    Var_PK_AG = 0,
    Var_lnPK_AG = 0,
    Var_PF_AG = 0,
    Var_lnPF_AG = 0,
    Var_PL_AG = 0,
    Var_lnPL_AG = 0,
    Var_PG_AG = 0,
    Var_lnPG_AG = 0,
    Var_PM_AG = 0,
    Var_lnPM_AG = 0,
    Var_PR_AG = 0,
    Var_lnPR_AG = 0,
    Var_PS_AG = 0,
    Var_lnPS_AG = 0,
    Var_kPAPS = 0,
    Var_lnkPAPS = 0,
    Var_kPAPS_syn = 0,
    Var_lnkPAPS_syn = 0,
    Var_kGA = 0,
    Var_lnkGA = 0,
    Var_kGA_syn = 0,
    Var_lnkGA_syn = 0,
    Var_CYP_Km = 0,
    Var_lnCYP_Km = 0,
    Var_CYP_VmaxC = 0,
    Var_lnCYP_VmaxC = 0,
    Var_UGT_Km = 0,
    Var_lnUGT_Km = 0,
    Var_UGT_VmaxC = 0,
    Var_lnUGT_VmaxC = 0,
    Var_UGT_Km_GA = 0,
    Var_lnUGT_Km_GA = 0,
    Var_UGT_Ki = 0,
    Var_lnUGT_Ki = 0,
    Var_Vmax_AG = 0,
    Var_lnVmax_AG = 0,
    Var_Km_AG = 0,
    Var_lnKm_AG = 0,
    Var_SULT_KVar_apap = 0,
    Var_lnSULT_Km_apap = 0,
    Var_SULT_KVar_paps = 0,
    Var_lnSULT_Km_paps = 0,
    Var_SULT_Ki = 0,
    Var_lnSULT_Ki = 0,
    Var_SULT_VmaxC = 0,
    Var_lnSULT_VmaxC = 0,
    Var_Vmax_AS = 0,
    Var_lnVmax_AS = 0,
    Var_Km_AS = 0,
    Var_lnKm_AS = 0,
    Verr_CPL_APAP_mcmolL = 0,
    Verr_CPL_APAP_mcgL = 0,
    Verr_CPL_AG_mcmolL = 0,
    Verr_CPL_AG_mcgL = 0,
    Verr_CPL_AS_mcmolL = 0,
    Verr_CPL_AS_mcgL = 0,
    Verr_CU_APAP_mcg = 0,
    Verr_CU_AG_mcg = 0,
    Verr_CU_AS_mcg = 0
  )

  if (!is.null(newParms)) {
    if (!all(names(newParms) %in% c(names(parms)))) {
      stop("illegal parameter name")
    }
    parms[names(newParms)] <- newParms
  }

  parms <- within(as.list(parms), {
    lnBW = log(70.);
    lnkSG_Vm = log(2332.5);
    lnkSG_Km = log(1765.49);
    lnBP_APAP = log(0.9);
    lnPF_APAP = log(0.447);
    lnPG_APAP = log(0.907);
    lnPK_APAP = log(0.711);
    lnPL_APAP = log(0.687);
    lnPM_APAP = log(0.687);
    lnPR_APAP = log(0.676);
    lnPS_APAP = log(0.606);
    lnPF_AS = log(0.088);
    lnPG_AS = log(0.297);
    lnPK_AS = log(0.261);
    lnPL_AS = log(0.203);
    lnPM_AS = log(0.199);
    lnPR_AS = log(0.207);
    lnPS_AS = log(0.254);
    lnPF_AG = log(0.128);
    lnPG_AG = log(0.436);
    lnPK_AG = log(0.392);
    lnPL_AG = log(0.321);
    lnPM_AG = log(0.366);
    lnPR_AG = log(0.364);
    lnPS_AG = log(0.351);
    lnkPAPS = log(0.018);
    lnkGA = log(0.008);
    lnIVDose_APAP_mgkg = log(2E-9);
    lnIVDose_APAP_mg = log(2E-9);
  })
  out <- .C("getParms",  as.double(parms),
            out=double(length(parms)),
            as.integer(length(parms)))$out
  names(out) <- names(parms)
  out
}

Outputs <- c(
    "CF_APAP",
    "CK_APAP",
    "CL_APAP",
    "CR_APAP",
    "CS_APAP",
    "CF_AS",
    "CK_AS",
    "CL_AS",
    "CR_AS",
    "CS_AS",
    "CF_AG",
    "CK_AG",
    "CL_AG",
    "CR_AG",
    "CS_AG",
    "CA_APAP",
    "CV_APAP",
    "CPL_APAP",
    "CA_AS",
    "CV_AS",
    "CPL_AS",
    "CA_AG",
    "CV_AG",
    "CPL_AG",
    "CPL_APAP_mcmolL",
    "CPL_APAP_mcgL",
    "CPL_AG_mcmolL",
    "CPL_AG_mcgL",
    "CPL_AS_mcmolL",
    "CPL_AS_mcgL",
    "CL_APAP_mcmolL",
    "CL_APAP_mcgL",
    "CU_APAP_mcg",
    "CU_AG_mcg",
    "CU_AS_mcg",
    "f_abs",
    "lnCPL_APAP_mcgL",
    "lnCPL_AG_mcgL",
    "lnCPL_AS_mcgL",
    "lnCU_APAP_mcg",
    "lnCU_AG_mcg",
    "lnCU_AS_mcg",
    "lnf_abs",
    "Verr_lnCPL_APAP_mcmolL",
    "Verr_lnCPL_APAP_mcgL",
    "Verr_lnCPL_AG_mcmolL",
    "Verr_lnCPL_AG_mcgL",
    "Verr_lnCPL_AS_mcmolL",
    "Verr_lnCPL_AS_mcgL",
    "Verr_lnCU_APAP_mcg",
    "Verr_lnCU_AG_mcg",
    "Verr_lnCU_AS_mcg"
)

initStates <- function(parms, newStates = NULL) {
  Y <- c(
    CL_APAP_to_NAPQI_CYP = 0.0,
    CL_APAP_to_AS_SULT = 0.0,
    CL_APAP_to_AG_UGT = 0.0,
    AST_Oral_APAP = 0.0,
    AST_APAP = 0.0,
    AST_to_Gut_APAP = 0.0,
    AF_APAP = 0.0,
    AR_APAP = 0.0,
    AS_APAP = 0.0,
    AF_AS = 0.0,
    AR_AS = 0.0,
    AS_AS = 0.0,
    AF_AG = 0.0,
    AR_AG = 0.0,
    AS_AG = 0.0,
    AKE_APAP = 0.0,
    AKE_AS = 0.0,
    AKE_AG = 0.0,
    AK_APAP = 0.0,
    AK_AS = 0.0,
    AK_AG = 0.0,
    AL_APAP = 0.0,
    AL_AS = 0.0,
    AL_AG = 0.0,
    AL_PAPS = 0.0,
    AL_GA = 0.0,
    CH_AG = 0.0,
    CH_AG_to_CL_AG = 0.0,
    CH_AS = 0.0,
    CH_AS_to_CL_AS = 0.0,
    AM_APAP = 0.0,
    AM_AS = 0.0,
    AM_AG = 0.0,
    ABLA_APAP = 0.0,
    ABLA_AS = 0.0,
    ABLA_AG = 0.0,
    ABL_IV_APAP = 0.0,
    ABLV_APAP = 0.0,
    ABLV_AS = 0.0,
    ABLV_AG = 0.0,
    AU_APAP = 0.0,
    AU_AS = 0.0,
    AU_AG = 0.0,
    pct_abs = 0.0
  )

  Y <- within(c(as.list(parms),as.list(Y)), {
    Y["AL_PAPS"] <- 1. 
    Y["AL_GA"] <- 1. 

  })$Y

  if (!is.null(newStates)) {
    if (!all(names(newStates) %in% c(names(Y)))) {
      stop("illegal state variable name in newStates")
    }
    Y[names(newStates)] <- newStates
  }

.C("initState", as.double(Y));
Y
}
