---
title: "Convergence_NB"
output:
  html_document:
    df_print: paged
  html_notebook: false
---

```{r message = FALSE, warning=FALSE}
# Install the pksensi, if the package haven't already:
# devtools::install_github("nanhung/pksensi")

# Import the pksensi
library(pksensi)
library(EnvStats) # To use "qnormTrunc"

```

# Exercise: Flip-Flop Kinetics (Analytical approach)

```{r message = FALSE}
#
FFPK <- function(parameters, times, dose = 320){
  A <- (dose * parameters[1])/( parameters[3]*( parameters[1]- parameters[2]))
  CONC <- A*exp(- parameters[2] * times) - A*exp(- parameters[1] * times)
  return(CONC)
}

FFPK <- pksensi:::FFPK
```


## Uniform distribution

```{r message = FALSE}
q1 = "qunif"
q1.arg = list(list(min = 0.5,  max = 1.5), 
             list(min = 0.02, max = 0.3),
             list(min = 20, max = 60))

# The replication and confidence interval are set to 20, 0.95, respectively.
set.seed(1234)
x1<-rfast99(factors=c("KA","KE","V"),
           n = 400, q = q1, q.arg = q1.arg, rep = 20, conf = 0.95)

# Parameter space for each parameter across replication
plot(x1$a[,1,"KA"], x1$a[,2,"KA"])
plot(x1$a[,1,"KE"], x1$a[,2,"KE"])
plot(x1$a[,1,"V"], x1$a[,2,"V"])
```


```{r message = FALSE}
times <- seq(from = 0.25, to = 24.25, by = 0.5)
y1<-solve_fun(x1, model = FFPK, time = times, output = "output")
tell2(x1,y1)
pksim(y1)
```

```{r message = FALSE}
check(x1, SI = 0.05, CI = 0.01)
heat_check(x1)
heat_check(x1, index = "CI", CI.cutoff = c(0.01,0.05))
plot(x1) # Visualize the printed result 
```

```{r message = FALSE}
plot(x1$a[,1,"KA"], y1[,1,1,]) # rep = 1; time = 0.25
plot(x1$a[,1,"KE"], y1[,1,1,])
plot(x1$a[,1,"V"], y1[,1,1,])

plot(x1$a[,,"KA"], x1$a[,,"KE"])
plot(x1$a[,,"KA"], x1$a[,,"V"])
plot(x1$a[,,"KE"], x1$a[,,"V"])
```

## Truncated normal distribution

```{r message = FALSE}
q2 = "qnormTrunc"

mu_KA <- mean(x1$a[,,"KA"]) 
sd_KA <- sd(x1$a[,,"KA"])
mu_KE <-mean(x1$a[,,"KE"])
sd_KE <- sd(x1$a[,,"KE"])
mu_V <- mean(x1$a[,,"V"])
sd_V <- sd(x1$a[,,"V"])

q2.arg = list(list(mean = mu_KA, sd = sd_KA, min = 0.5,  max = 1.5), 
             list(mean = mu_KE, sd = sd_KE, min = 0.02, max = 0.3),
             list(mean = mu_V, sd = mu_V, min = 20, max = 60))

set.seed(1234)
x2<-rfast99(factors=c("KA","KE","V"),
           n = 400, q = q2, q.arg = q2.arg, rep = 20, conf = 0.95)

# Parameter space for each parameter across replication
plot(x2$a[,1,"KA"], x2$a[,2,"KA"])
plot(x2$a[,1,"KE"], x2$a[,2,"KE"])
plot(x2$a[,1,"V"], x2$a[,2,"V"])
```


```{r message = FALSE}
y2<-solve_fun(x2, model = FFPK, time = times, output = "output")
tell2(x2,y2)
pksim(y2)
```

```{r message = FALSE}
check(x2, SI = 0.05, CI = 0.01)
heat_check(x2)
heat_check(x2, index = "CI", CI.cutoff = c(0.01,0.05))
plot(x2) # Visualize the printed result 
```


```{r message = FALSE}
plot(x2$a[,1,"KA"], y2[,1,1,]) # rep = 1; time = 0.25
plot(x2$a[,1,"KE"], y2[,1,1,])
plot(x2$a[,1,"V"], y2[,1,1,])

plot(x2$a[,,"KA"], x2$a[,,"KE"])
plot(x2$a[,,"KA"], x2$a[,,"V"])
plot(x2$a[,,"KE"], x2$a[,,"V"])
```