infile.name <- "APAP.setpoint.in"
outfile.name <- "setpoint.csv"
conditions <- "mgkg_flag = 0; OralExp_APAP = NDoses(2, 1 0, 0 0.75); OralDur_APAP = 0.75; OralDose_APAP_mg = 1000.0; IVExp_APAP = 0.; IVDose_APAP_mg = 0.;"

parameters<-c("lnTg", "lnTp",
              "lnCYP_Km","lnCYP_VmaxC",
              "lnSULT_Km_apap","lnSULT_Ki","lnSULT_Km_paps","lnSULT_VmaxC",
              "lnUGT_Km","lnUGT_Ki","lnUGT_Km_GA","lnUGT_VmaxC",
              "lnKm_AG","lnVmax_AG","lnKm_AS","lnVmax_AS",
              "lnkGA_syn","lnkPAPS_syn",
              "lnCLC_APAP","lnCLC_AG","lnCLC_AS")
output <- c("lnCPL_APAP_mcgL", "lnCPL_AG_mcgL", "lnCPL_AS_mcgL")
times <- seq(from = 0.01, to = 12.01, by = 0.4)
rtol <- 1e-6
atol <- 1e-9


mName<-"APAP_PBPK_thera"


y<-solve_MCSim(x, mName = mName,
            infile.name = infile.name, 
            outfile.name = outfile.name, 
            setpoint.data = setpoint.data,
            parameters = parameters,
            output = output,
            time = times, 
            condition = conditions,
            rm.outfile = T)

solve_MCSim <- function(x, mName, infile.name, outfile.name, setpoint.data,
                        parameters = NULL, 
                        output  = NULL, 
                        time  = NULL, 
                        condition  = NULL,
                        rm.outfile = T){
  
  if(file.exists(infile.name) == F){
    gen_infile(infile.name = infile.name, 
               outfile.name = outfile.name, 
               setpoint.data = setpoint.data,
               parameters = parameters,
               output = output,
               time = times, 
               condition = conditions)
  }
  
  mcsim. <- paste0("mcsim.", mName)
  
  if(file.exists(mcsim.) == F){
    system(paste0("makemcsim", " ", mName, ".model"))
  }
  
  #
  n.sample <- length(x$s)
  n.factors <- ifelse(class(x$factors) == "character", length(x$factors), x$factors)
  n.rep <- x$rep
  n.time <- ifelse(is.null(times), 1, length(times))
  n.vars <- length(output)
  dim <- c(n.sample * n.factors, n.rep, n.time, n.vars)
  
  #
  X <- cbind(1, apply(x$a, 3L, c))
  write.table(X, file=setpoint.data, row.names=F, sep="\t")
  system(paste0("./mcsim.", mName, " ", infile.name))
  str <- length(x$factors) + 2
  
  df <- as.data.frame(data.table::fread("setpoint.csv", head = T))
  
  #
  if (rm.outfile == T){
    file.remove(outfile.name)
    file.remove(setpoint.data) 
  }

  y <- df[,str:ncol(df)] %>% as.matrix() # output only
  dim(y)<- dim
  dimnames(y)[[3]] <- times
  dimnames(y)[[4]] <- output
  return(y)
}





gen_infile <- function(infile.name, outfile.name, setpoint.data, parameters, output, time,
                       condition, rtol = 1e-6, atol = 1e-9){
  cat("#---------------------------------------- \n#",
      " ", infile.name , "\n#",
      " (Generated by gen_infile)\n#",
      "----------------------------------------", "\n\n",
      file = infile.name, sep = "")
  
  cat("Integrate (Lsodes, ", rtol, ", ", atol, " , 1);", "\n\n", file=infile.name,append=TRUE,sep="")
  cat("SetPoints (", "\n",
      "\"", outfile.name, "\", \n\"",setpoint.data,"\",\n",
      "0, ", "\n",
      paste(parameters, collapse=", "),");\n\n",
      file = infile.name, append=TRUE, sep="")
  
  cat("#---------------------------------------- \n#",
      " Simulation scenario\n#",
      "----------------------------------------", "\n\n",
      file = infile.name, append=TRUE, sep = "")
  
  cat("Simulation {", "\n\n", file = infile.name, append=TRUE)
  
  cat(condition, "\n\n", file = infile.name, append=TRUE, sep = "")
  
  cat("Print (", paste(output, collapse=", "), ", ", paste(times, collapse=", "), ");\n\n",
      "}", "\n\n",
      file = infile.name, append=TRUE, sep="")
  
  cat("END.", file = infile.name, append=TRUE)
}



