---
title: "ViSA_NB"
output:
  html_document:
    df_print: paged
  html_notebook: default
---


```{r message = FALSE}
# Install the ViSA
# devtools::install_github("nanhung/ViSA")
```

## R Markdown

```{r message = FALSE, warning=FALSE}
# Import the packages
library(ViSA)
library(sensitivity)
library(tidyverse)

```



```{r message = FALSE}
# 
n <- 1000
set.seed(1234)
X1 <- data.frame(matrix(runif(8 * n), nrow = n))
X2 <- data.frame(matrix(runif(8 * n), nrow = n))
x <- soboljansen(model = NULL, X1, X2, nboot = 100)
y <- sobol.fun(x$X)
tell(x,y)
x
```


```{r message = FALSE}
# 
tell(x,y) %>% plot
```


```{r message = FALSE}
# 
tell(x,y) %>% converge
```

```{r message = FALSE}
# 
tell(x,y) %>% converge %>% plot.converge
```

```{r message = FALSE}
parameters<-c("k01","k12", "k23", "k34", "k45","k56", "k67", "k78")
tell(x,y) %>% converge(parameters) %>% plot.converge
```


```{r message = FALSE}
set.seed(1234)
convergejansen(n = 1000, n.factors = 8, X = sobol.X, fun = sobol.fun) 
```

```{r message = FALSE}
set.seed(1234)
convergejansen(n = 1000, n.factors = 8, X = sobol.X, fun = sobol.fun) %>% 
  converge.plot
```

```{r message = FALSE}
set.seed(1234)
convergejansen(n = 1000, n.factors = 8, X = sobol.X, fun = sobol.fun, order = "S") %>% 
  converge.plot
```

```{r message = FALSE}
#
test.X<- function(n){
  data.frame(k01 = runif(n, 0, 1),
             k12 = runif(n, 0, 1),
             k23 = runif(n, 0, 1),
             k34 = runif(n, 0, 1),
             k45 = runif(n, 0, 1),
             k56 = runif(n, 0, 1),
             k67 = runif(n, 0, 1),
             k78 = runif(n, 0, 1),
             k89 = runif(n, 0, 1),
             k90 = runif(n, 0, 1))
}
```


```{r message = FALSE}
set.seed(1234)
convergejansen(n = 1000, n.factors = 10, X = test.X, fun = sobol.fun, order = "S") %>% 
  converge.plot
set.seed(1234)
convergejansen(n = 1000, n.factors = 10, X = test.X, fun = sobol.fun) %>% 
  converge.plot
```


